/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Doctor;

/**
 *
 * @author jsmr0
 */
public class ServicioVista extends javax.swing.JFrame {
    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form VentanaPrincipal1
     */
    public ServicioVista() {
        abrirVentana();
        initComponents();
        crearTabla();
    }
    
    private void abrirVentana(){
        setTitle ("Juego de Memoria");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true); 
        setResizable(false);
        setLayout(null);    
    }   
    
    private void crearTabla(){
        String[] titulo=new String[]{"Nombres", "Apellido", 
            "Sexo", "Horario Cita", "Telefono", 
            "Dirección", "Número de ID", "Servicio"};
        dtm.setColumnIdentifiers(titulo);
        TablaPacientes.setModel(dtm);
    }
    
    public void llenarTabla(){
        dtm.addRow(new Object[]{
            CampoNombres.getText(),
            CampoApellidos.getText(),
            CampoID.getText()
        });
    }
    
    public String[]servicios(String servicios){
        String[]nombresDeDoctores = new String[5];       
        if(servicios.equalsIgnoreCase("Odontología")){
            nombresDeDoctores[0]="Odontologo 1";
            nombresDeDoctores[1]="Odontologo 2";
            nombresDeDoctores[2]="Odontologo 3";
            nombresDeDoctores[3]="Odontologo 4";
            nombresDeDoctores[4]="Odontologo 5";            
        }
        if(servicios.equalsIgnoreCase("Examen de Laboratorio")){
            nombresDeDoctores[0]="Lab 1";
            nombresDeDoctores[1]="Lab 2";
            nombresDeDoctores[2]="Lab 3";
            nombresDeDoctores[3]="Lab 4";
            nombresDeDoctores[4]="Lab 5";            
        }        
        if(servicios.equalsIgnoreCase("Cita General")){
            nombresDeDoctores[0]="Medico General 1";
            nombresDeDoctores[1]="Medico General 2";
            nombresDeDoctores[2]="Medico General 3";
            nombresDeDoctores[3]="Medico General 4";
            nombresDeDoctores[4]="Medico General 5";            
        }  
        if(servicios.equalsIgnoreCase("Cita con Especialista")){
            nombresDeDoctores[0]="Especialista 1";
            nombresDeDoctores[1]="Especialista 2";
            nombresDeDoctores[2]="Especialista 3";
            nombresDeDoctores[3]="Especialista 4";
            nombresDeDoctores[4]="Especialista 5";            
        }         
        return nombresDeDoctores;
    }
    
    public String getNombre(){
        return CampoNombres.getText();
    }
    
    public String getApellidos(){
        return CampoApellidos.getText();
    }    
    
    public float getNumeroID(){
        return (int) Float.parseFloat(CampoID.getText());
    }
    
    public void displayErrorMessage(String erroMessage) {
        JOptionPane.showMessageDialog(this, erroMessage);
    }    

    public void addBotonAgregarListener(ActionListener listenControles){
        BotonAgregar.addActionListener(listenControles);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        jPanelBusqueda = new javax.swing.JPanel();
        CampoBuscarID = new javax.swing.JTextField();
        BotonBuscarID = new javax.swing.JButton();
        jPanelContenido = new javax.swing.JPanel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPacientes = new javax.swing.JTable();
        jLabelInfoTabla = new javax.swing.JLabel();
        PanelCamposTexto = new javax.swing.JPanel();
        ContenedorDatosPersonales = new javax.swing.JPanel();
        LabelSubtitulo1 = new javax.swing.JLabel();
        LabelNombres = new javax.swing.JLabel();
        CampoNombres = new javax.swing.JTextField();
        Label1erApellido = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        CampoID = new javax.swing.JTextField();
        LabelTipoID = new javax.swing.JLabel();
        ChooseTipoID = new javax.swing.JComboBox<>();
        LabelSexo = new javax.swing.JLabel();
        ChooserSexo = new javax.swing.JComboBox<>();
        jPanelDatosContacto = new javax.swing.JPanel();
        CampoCelular = new javax.swing.JTextField();
        CampoDireccion = new javax.swing.JTextField();
        LabelCelular = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        LabelSubtitulo2 = new javax.swing.JLabel();
        LabelEPS = new javax.swing.JLabel();
        ChooserEPS = new javax.swing.JComboBox<>();
        PanelCita = new javax.swing.JPanel();
        LabelSubtitulo3 = new javax.swing.JLabel();
        LabelServicio = new javax.swing.JLabel();
        ChooserServicio = new javax.swing.JComboBox<>();
        LabelMedico = new javax.swing.JLabel();
        ChooserMedico = new javax.swing.JComboBox<>();
        LabelFecha = new javax.swing.JLabel();
        ChooserFecha = new com.toedter.calendar.JDateChooser();
        LabelHora = new javax.swing.JLabel();
        ChooserHora = new javax.swing.JComboBox<>();
        LabelLugar = new javax.swing.JLabel();
        ChooserLugar = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        BotonExportarCitas = new javax.swing.JButton();
        BotonRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitulo.setText("Servicio de Salud de Univalle");
        LabelTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanelBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        jPanelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CampoBuscarID.setEditable(false);
        CampoBuscarID.setText("Buscar por cedula");
        CampoBuscarID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarIDActionPerformed(evt);
            }
        });

        BotonBuscarID.setText("*lupa*");
        BotonBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBusquedaLayout = new javax.swing.GroupLayout(jPanelBusqueda);
        jPanelBusqueda.setLayout(jPanelBusquedaLayout);
        jPanelBusquedaLayout.setHorizontalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(CampoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(BotonBuscarID)
                .addContainerGap(721, Short.MAX_VALUE))
        );
        jPanelBusquedaLayout.setVerticalGroup(
            jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarID))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 60));

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTabla.setPreferredSize(new java.awt.Dimension(1000, 120));

        TablaPacientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaPacientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaPacientes);
        if (TablaPacientes.getColumnModel().getColumnCount() > 0) {
            TablaPacientes.getColumnModel().getColumn(2).setMinWidth(50);
            TablaPacientes.getColumnModel().getColumn(2).setPreferredWidth(50);
            TablaPacientes.getColumnModel().getColumn(2).setMaxWidth(50);
            TablaPacientes.getColumnModel().getColumn(4).setMinWidth(100);
            TablaPacientes.getColumnModel().getColumn(4).setPreferredWidth(100);
            TablaPacientes.getColumnModel().getColumn(4).setMaxWidth(100);
            TablaPacientes.getColumnModel().getColumn(7).setMinWidth(60);
            TablaPacientes.getColumnModel().getColumn(7).setPreferredWidth(60);
            TablaPacientes.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        jLabelInfoTabla.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelInfoTabla.setText("Lista de citas programadas:");

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCamposTexto.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorDatosPersonales.setBackground(new java.awt.Color(255, 255, 255));

        LabelSubtitulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelSubtitulo1.setText("Datos Personales:");

        LabelNombres.setText("Nombres: ");

        Label1erApellido.setText("Apellidos:");

        LabelID.setText("Nro. de Identificación:");

        LabelTipoID.setText("Tipo de Identificación:");

        ChooseTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Tarjeta de Identidad", "Cedula de Ciudadanía", "Cedula de Extranjería", "Contraseña" }));

        LabelSexo.setText("Sexo de nacimiento:");

        ChooserSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Masculino", "Femenino" }));

        javax.swing.GroupLayout ContenedorDatosPersonalesLayout = new javax.swing.GroupLayout(ContenedorDatosPersonales);
        ContenedorDatosPersonales.setLayout(ContenedorDatosPersonalesLayout);
        ContenedorDatosPersonalesLayout.setHorizontalGroup(
            ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombres)
                            .addComponent(Label1erApellido)))
                    .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LabelSubtitulo1))
                    .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelID)
                        .addGap(28, 28, 28)
                        .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoID, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(CampoApellidos)
                            .addComponent(CampoNombres)))
                    .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTipoID)
                            .addComponent(LabelSexo))
                        .addGap(18, 18, 18)
                        .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChooserSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChooseTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        ContenedorDatosPersonalesLayout.setVerticalGroup(
            ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorDatosPersonalesLayout.createSequentialGroup()
                .addComponent(LabelSubtitulo1)
                .addGap(18, 18, 18)
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombres)
                    .addComponent(CampoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1erApellido)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelID)
                    .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipoID)
                    .addComponent(ChooseTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSexo)
                    .addComponent(ChooserSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanelDatosContacto.setBackground(new java.awt.Color(255, 255, 255));

        CampoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDireccionActionPerformed(evt);
            }
        });

        LabelCelular.setText("Celular:");

        LabelDireccion.setText("Dirección:");

        LabelTelefono.setText("Telefono:");

        LabelEmail.setText("Email:");

        LabelSubtitulo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelSubtitulo2.setText("Datos de Contacto:");

        LabelEPS.setText("EPS:");

        ChooserEPS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Sura", "Sanitas", "Nueva EPS", "Compensar", "Salud Total", "Med Plus" }));

        javax.swing.GroupLayout jPanelDatosContactoLayout = new javax.swing.GroupLayout(jPanelDatosContacto);
        jPanelDatosContacto.setLayout(jPanelDatosContactoLayout);
        jPanelDatosContactoLayout.setHorizontalGroup(
            jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDireccion)
                            .addComponent(LabelTelefono)
                            .addComponent(LabelCelular)
                            .addComponent(LabelEmail)
                            .addComponent(LabelEPS))
                        .addGap(39, 39, 39)
                        .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoDireccion)
                            .addComponent(CampoTelefono)
                            .addComponent(CampoCelular)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(ChooserEPS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelDatosContactoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LabelSubtitulo2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelDatosContactoLayout.setVerticalGroup(
            jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubtitulo2)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelDireccion)
                    .addComponent(CampoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefono)
                    .addComponent(CampoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCelular)
                    .addComponent(CampoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEPS)
                    .addComponent(ChooserEPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCita.setBackground(new java.awt.Color(255, 255, 255));

        LabelSubtitulo3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelSubtitulo3.setText("Detalles de la cita medica:");

        LabelServicio.setText("Servicio requerido:");

        ChooserServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Odontología", "Examen de Laboratorio", "Cita General", "Cita con Especialista" }));
        ChooserServicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChooserServicioItemStateChanged(evt);
            }
        });
        ChooserServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooserServicioActionPerformed(evt);
            }
        });

        LabelMedico.setText("Doctor encargado:");

        ChooserMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "--", "--", "--", "--" }));

        LabelFecha.setText("Fecha:");

        ChooserFecha.setMaxSelectableDate(new java.util.Date(1704002463000L));
        ChooserFecha.setMinSelectableDate(new java.util.Date(1672552863000L));

        LabelHora.setText("Hora:");

        ChooserHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 M", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM" }));

        LabelLugar.setText("Lugar:");

        ChooserLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "HUV San Fernando", "HUV Sede Norte", "Servicio Medico Melendez" }));

        javax.swing.GroupLayout PanelCitaLayout = new javax.swing.GroupLayout(PanelCita);
        PanelCita.setLayout(PanelCitaLayout);
        PanelCitaLayout.setHorizontalGroup(
            PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelSubtitulo3)
                .addGap(48, 48, 48))
            .addGroup(PanelCitaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelServicio)
                    .addComponent(LabelMedico)
                    .addComponent(LabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHora)
                    .addComponent(LabelLugar))
                .addGap(32, 32, 32)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChooserServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChooserMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChooserHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChooserLugar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelCitaLayout.setVerticalGroup(
            PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSubtitulo3)
                .addGap(18, 18, 18)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelServicio)
                    .addComponent(ChooserServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMedico)
                    .addComponent(ChooserMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChooserFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHora)
                    .addComponent(ChooserHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLugar)
                    .addComponent(ChooserLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonModificar.setText("MODIFICAR");

        BotonEliminar.setText("ELIMINAR");

        BotonNuevo.setText("NUEVO");

        BotonExportarCitas.setText("EXPORTAR");

        BotonRestaurar.setText("RESTAURAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(BotonNuevo)
                .addGap(62, 62, 62)
                .addComponent(BotonAgregar)
                .addGap(54, 54, 54)
                .addComponent(BotonModificar)
                .addGap(58, 58, 58)
                .addComponent(BotonEliminar)
                .addGap(62, 62, 62)
                .addComponent(BotonExportarCitas)
                .addGap(71, 71, 71)
                .addComponent(BotonRestaurar)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BotonExportarCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonRestaurar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BotonAgregar)
                                .addComponent(BotonModificar)
                                .addComponent(BotonNuevo)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCamposTextoLayout = new javax.swing.GroupLayout(PanelCamposTexto);
        PanelCamposTexto.setLayout(PanelCamposTextoLayout);
        PanelCamposTextoLayout.setHorizontalGroup(
            PanelCamposTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCamposTextoLayout.createSequentialGroup()
                .addGroup(PanelCamposTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCamposTextoLayout.createSequentialGroup()
                        .addComponent(ContenedorDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatosContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        PanelCamposTextoLayout.setVerticalGroup(
            PanelCamposTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCamposTextoLayout.createSequentialGroup()
                .addGroup(PanelCamposTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCamposTextoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ContenedorDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelDatosContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCamposTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCamposTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        jPanel1.add(jPanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscarIDActionPerformed

    private void BotonBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarIDActionPerformed

    private void CampoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDireccionActionPerformed

    private void ChooserServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooserServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooserServicioActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed

    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void ChooserServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChooserServicioItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ChooserServicio.getSelectedIndex()>0){
                this.ChooserMedico.setModel(new DefaultComboBoxModel(this.servicios(this.ChooserServicio.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ChooserServicioItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscarID;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonExportarCitas;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonRestaurar;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoBuscarID;
    private javax.swing.JTextField CampoCelular;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoNombres;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JComboBox<String> ChooseTipoID;
    private javax.swing.JComboBox<String> ChooserEPS;
    private com.toedter.calendar.JDateChooser ChooserFecha;
    private javax.swing.JComboBox<String> ChooserHora;
    private javax.swing.JComboBox<String> ChooserLugar;
    private javax.swing.JComboBox<String> ChooserMedico;
    private javax.swing.JComboBox<String> ChooserServicio;
    private javax.swing.JComboBox<String> ChooserSexo;
    private javax.swing.JPanel ContenedorDatosPersonales;
    private javax.swing.JLabel Label1erApellido;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelEPS;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelLugar;
    private javax.swing.JLabel LabelMedico;
    private javax.swing.JLabel LabelNombres;
    private javax.swing.JLabel LabelServicio;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JLabel LabelSubtitulo1;
    private javax.swing.JLabel LabelSubtitulo2;
    private javax.swing.JLabel LabelSubtitulo3;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JLabel LabelTipoID;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelCamposTexto;
    private javax.swing.JPanel PanelCita;
    private javax.swing.JTable TablaPacientes;
    private javax.swing.JLabel jLabelInfoTabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelDatosContacto;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
